CREATE DATABASE IF NOT EXISTS weather_app;
USE weather_app;

CREATE TABLE IF NOT EXISTS weather_data (
	id INT AUTO_INCREMENT PRIMARY KEY,
	latitude FLOAT NOT NULL,
	longitude FLOAT NOT NULL,
	temperature VARCHAR(50),
	windspeed VARCHAR(50),
	saved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
