CREATE DATABASE IF NOT EXISTS weather_app;
USE weather_app;

CREATE TABLE IF NOT EXISTS weather_data (
	id INT AUTO_INCREMENT PRIMARY KEY,
	city VARCHAR(255),
	temperature VARCHAR(50),
	saved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
